### ISSUE TITLE
Hover over headers to get the details of it

### ISSUE THREAD

**Issue by vibhormittal21** [VarunS2002/Python-NSE-Option-Chain-Analyzer#11]
@VarunS2002 Firstly I really appreciate this piece of art. It works brilliantly with great insights into option strike price data. 
As a new user, I am continuously struggling to remember how each insight or data point is being calculated. 
It will be awesome if we can add the details for each insight from Wiki whenever we hover our mouse over it.

**Comment by VarunS2002** [comment]
@vibhormittal21 
Description of the data displayed is available here: https://github.com/VarunS2002/Python-NSE-Option-Chain-Analyzer#data-displayed
Since it is too big, it won't be added in the program.
The formula for calculation is complicated and hence isn't documented. You will have to refer the code for that.

**Comment by vibhormittal21** [comment]
Okay. Thanks again!
